config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'finder#index'

  get 'finder/pokemon' => 'finder#pokemon', as: 'pokemon'

  get 'finder/magic' => 'finder#magic', as: 'magic'

  get 'finder/yugioh' => 'finder#yugioh', as: 'yugioh'

  get '/admin' => 'admin/dashboard#index ', as: 'admin'

  get 'finder/search_results' => 'finder#search_results', as: 'search_results'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  validates :name, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category

  validates :name, :condition, :price, :stock_quantity, presence: true

  validates :condition, inclusion: {
    in: %w(mint played),
    message: "must be 'mint' or 'played' not %{value}"
  }

  validates :price, :stock_quantity, numericality: {
    greater_than_or_equal_to: 0
  }

  validates :price, format: {
    with: /\A\d+(?:\.\d{0,2})?\z/,
    message: "must be 0..2 decimal places."
  }

  validates :stock_quantity, numericality: {
    only_integer: true
  }

  validates :image_filename, allow_blank: true, format: {
    with: %r{\.gif|jpg|png}i,
    message: "must end with .gif, .jpg, or .png"
  }

  # mount_uploader :image_filename, CardUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/finder_controller.rb
class FinderController < ApplicationController
  def index
    @products_mint = Product.where(condition: 'mint')
  end

  # def show
  #   @product = Product.find(params[:id])
  # end

  def search_results
    wildcard_keywords = '%' + params[:search_keywords] + '%'
    @products = Product.where("name LIKE ?", wildcard_keywords)
  end

  def pokemon
    @pokemon = Product.where(category_id: 1).where(condition: 'mint').order(:name)
  end

  def magic
    @magic = Product.where(category_id: 2).where(condition: 'mint').order(:name)
  end

  def yugioh
    @yugioh = Product.where(category_id: 3).where(condition: 'mint').order(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/finder_helper.rb
module FinderHelper
end

app/views/finder/index.html.erb
<h1>Hobbystation</h1>

<div id="wrapper">
  <%= render @products_mint %>
  <%#<%= render @products_played %>
</div>

app/views/finder/magic.html.erb
<section id="main" class="right">
  <%= render @magic %>
  <%#<%= render @products_played %>
</section>

app/views/finder/pokemon.html.erb
<section id="main" class="right">
  <%= render @pokemon %>
</section>

app/views/finder/search_results.html.erb
<section id="main" class="right">
  <h2>Search Results</h2>
  <% if @products.size.zero? %>
    <p>No Products found.</p>
  <% else %>
    <%= render @products %>
  <% end %>
</section>

app/views/finder/show.html.erb
<section id="main" class="right">
  
</section>

app/views/finder/yugioh.html.erb
<section id="main" class="right">
  <%= render @yugioh %>
  <%#<%= render @products_played %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hobbystation</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <header class="block">
      <h1 class="left">Hobbystation</h1>
      <%= form_tag search_results_path, method: :get do %>
        <%= text_field_tag :search_keywords %>
        <%= submit_tag 'Search', class: "right" %>
      <% end %>
    </header>

    <%= yield %>

    <aside>
      <nav>
        <ul>
          <li><%= link_to 'Show All', root_path %></li>
          <li><%= link_to 'Pokemon', pokemon_path %></li>
          <li><%= link_to 'Magic: The Gathering', magic_path %></li>
          <li><%= link_to 'Yu-Gi-Oh!', yugioh_path %></li>
        </ul>
      </nav>
    </aside>

    <footer class="clear">
      <p><%= link_to 'Admin Login', admin_path %></p>
    </footer>
  </div>

</body>
</html>

app/views/products/_product.html.erb
<div class="product block">
  <h3><%= product.name %></h3>
    <div class="left">
      <% if product.image_filename.present? %>
        <%= image_tag(product.image_filename) %>
      <% end %>
    </div>
    <div class="description">
      <h4>Flavor Text:</h4>
      <p><%= product.flavor_text %></p>
      <h5>Category:</h5>
      <% if product.category.present? %>
        <p><%= product.category.name %></p>
      <% end %>
    </div>
  <div style="text-align: right;" class="clear">
    <form action="#" method="post">
      <%= radio_button_tag(:condition, "mint_#{product.id}", true) %>
      Mint
      <%= radio_button_tag(:condition, "played_#{product.id}") %>
      Played
      <%= select(:quantity, product.id, (0..product.stock_quantity).collect {| quantity | [ "#{quantity}", quantity ] }) %>
      <strong><%= number_to_currency(product.price) %></strong>
      <%= button_tag("Add to cart") %>
    </form>
  </div>
</div>